### ISSUE TITLE
Infinity loop

### ISSUE THREAD

**Issue by namnm1991** [KyberNetwork/reserve-stats#76]
If the trade logs crawler run with no toBlock specify ( daemon is True) and the worker pool encounter error, it will try again & again, into infinity loop. We should have a max attempts number here.

https://github.com/KyberNetwork/reserve-stats/blob/1c6112c365708f74739055fd09d250ca901df206/tradelogs/cmd/trade-logs-crawler/main.go#L250

**Comment by namnm1991** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [TradeLog Crawler Infinity loop](https://trello.com/c/XuZI7V0k/319-tradelog-crawler-infinity-loop)

**Comment by favadi** [comment]
PR merged.
